//
// Created by andrew on 12.04.18.
//

#ifndef BIZARRETALE_CONST_DEFINITIONS_H
#define BIZARRETALE_CONST_DEFINITIONS_H

#define TILE_SIZE_DEFAULT 64
#define WINDOW_SIZE_HD_WIDTH 1280
#define WINDOW_SIZE_HD_HEIGHT 720

#endif //BIZARRETALE_CONST_DEFINITIONS_H
