//
// Created by andrew on 12.04.18.
//

#ifndef BIZARRETALE_CONST_DEFINITIONS_H
#define BIZARRETALE_CONST_DEFINITIONS_H

#define TILE_SIZE_DEFAULT 64
#define WINDOW_SIZE_FULLHD_WIDTH 1920
#define WINDOW_SIZE_FULLHD_HEIGHT 1080
#define WINDOW_SIZE_HD_WIDTH 1280
#define WINDOW_SIZE_HD_HEIGHT 720
#define INFO_PANEL_TEXT_SIZE 12

#endif //BIZARRETALE_CONST_DEFINITIONS_H
